[workspace]

members = [
    "assembler",
    "disassembler",
    "rfvp",
    "rfvp-audio",
    "rfvp-core", "rfvp-debugger",
    "rfvp-render",
    "rfvp-tasks",
    "rfvp-video",
    "rfvp-wrld",
    "video_player",
]
