[package]
name = "rfvp-script"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"

anyhow = { workspace = true }
bytes = { workspace = true }
twofloat = { workspace = true }

env_logger = "0.11.3"
log = "0.4.21"
encoding_rs = "0.8.34"
binrw = "0.14.0"
